database:
  host: localhost
  port: 3306
  database: database
  user: root
  password: password
factions:
  perMemberChunks: 3
  maxFactionSize: 5
wars:
  membersOnlineToStartWar: 3
  enabled: false
  graceDurationInMinutes: 60
tablist:
  serverName: ยง6SMPFactions
  showServerName: true
  showOnlinePlayers: true
  showIngameTime: true
  # This option is the only way for users to see information about the war they are in.
  showOngoingWars: true